export const Sidebar: React.FC = () => {
    return (
        <div className="min-w-[300px] py-4 px-2 overflow-y-auto">
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
            <h1>Sidebar</h1>
        </div>
    )
}